# Generated by Django 5.2.11 on 2026-10-04 23:32

import django.db.models.deletion
import hashid_field.field
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('multitenancy', '0028_organization_onboarding_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='multitenancy.tenant',
                        verbose_name='Tenant',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('environment', models.CharField(max_length=8)),
                ('context_nip', models.CharField(max_length=20)),
                ('ksef_number', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=256)),
                ('direction', models.CharField(max_length=8)),
                ('kind', models.CharField(max_length=20)),
                ('issue_date', models.DateField()),
                ('permanent_storage_date', models.DateTimeField()),
                ('seller_name', models.CharField(blank=True, max_length=512)),
                ('seller_nip', models.CharField(blank=True, max_length=20)),
                ('buyer_name', models.CharField(blank=True, max_length=512)),
                ('buyer_nip', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('net', models.DecimalField(decimal_places=2, max_digits=24)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=24)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=24)),
                ('corrected_ksef_numbers', models.JSONField(blank=True, default=list)),
                ('raw_xml', models.TextField()),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='multitenancy.tenant',
                        verbose_name='Tenant',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='invoices.invoicecategory',
                    ),
                ),
            ],
            options={
                'ordering': ['-issue_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=256)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24, null=True)),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=24, null=True)),
                ('net', models.DecimalField(decimal_places=2, max_digits=24, null=True)),
                ('vat_rate', models.CharField(blank=True, max_length=32)),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice'
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='multitenancy.tenant',
                        verbose_name='Tenant',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceSyncState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(max_length=8)),
                ('context_nip', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('checkpoints', models.JSONField(default=dict)),
                ('last_success_at', models.DateTimeField(null=True)),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='multitenancy.tenant',
                        verbose_name='Tenant',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSyncRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='QUEUED', max_length=16)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('completed_subjects', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('pending_export', models.JSONField(default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='multitenancy.tenant',
                        verbose_name='Tenant',
                    ),
                ),
                (
                    'state',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='invoices.invoicesyncstate'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceImportError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ksef_number', models.CharField(max_length=64)),
                ('raw_xml', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('error_code', models.CharField(max_length=64)),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='multitenancy.tenant',
                        verbose_name='Tenant',
                    ),
                ),
                (
                    'state',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoicesyncstate'),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='invoicecategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='invoice_category_tenant_name'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'environment', 'issue_date'], name='invoices_in_tenant__6b4149_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'environment', 'ksef_number'), name='invoice_ksef_unique'
            ),
        ),
        migrations.AddConstraint(
            model_name='invoicesyncstate',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'environment', 'context_nip'), name='invoice_sync_context'
            ),
        ),
        migrations.AddConstraint(
            model_name='invoicesyncrun',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status__in', ['QUEUED', 'RUNNING'])),
                fields=('state',),
                name='one_active_invoice_sync',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoiceimporterror',
            constraint=models.UniqueConstraint(fields=('state', 'ksef_number'), name='invoice_import_error_unique'),
        ),
    ]
