# Generated by Django 5.2.11 on 2026-10-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoices', '0002_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesyncrun',
            name='execution_token',
            field=models.UUIDField(null=True),
        ),
    ]
