# Generated by Django 5.2.11 on 2026-10-09 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_documents(apps, schema_editor):
    Document = apps.get_model('demo', 'DocumentDemoItem')
    Membership = apps.get_model('multitenancy', 'TenantMembership')
    database = schema_editor.connection.alias
    for user_id in Document.objects.using(database).exclude(created_by_id=None).values_list('created_by_id', flat=True).distinct():
        organizations = list(Membership.objects.using(database).filter(
            user_id=user_id, is_accepted=True, tenant__type='organization'
        ).values_list('tenant_id', flat=True).distinct()[:2])
        if len(organizations) == 1:
            Document.objects.using(database).filter(created_by_id=user_id, tenant_id=None).update(tenant_id=organizations[0])


class Migration(migrations.Migration):
    dependencies = [
        ('demo', '0003_cruddemoitem_tenant'),
        ('multitenancy', '0030_remove_passkeys_manage_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdemoitem',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)s_set',
                to='multitenancy.tenant',
                verbose_name='Tenant',
            ),
        ),
        migrations.AlterField(
            model_name='documentdemoitem',
            name='created_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='documents',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(assign_existing_documents, migrations.RunPython.noop),
    ]
