# Generated by Django 5.2.11 on 2026-10-09 20:10

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('demo', '0004_organization_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdemoitem',
            name='file',
            field=models.FileField(max_length=255, upload_to=common.storages.OrganizationDocumentPathGenerator()),
        ),
    ]
