# Generated by Django 5.2.11 on 2026-10-03 18:28

import django.db.models.deletion
import hashid_field.field
from django.conf import settings
from django.db import migrations, models


def add_ksef_permissions(apps, schema_editor):
    """Seed the ksef.view / ksef.manage permissions and grant them to the ADMIN system role (OWNER gets all)."""
    from apps.multitenancy.constants import SystemRoleType
    from apps.multitenancy.permissions import get_all_permissions

    Permission = apps.get_model('multitenancy', 'Permission')
    OrganizationRole = apps.get_model('multitenancy', 'OrganizationRole')
    OrganizationRolePermission = apps.get_model('multitenancy', 'OrganizationRolePermission')

    ksef_codes = ['security.ksef.view', 'security.ksef.manage']
    for perm_def in get_all_permissions():
        if perm_def.code in ksef_codes:
            category_value = getattr(perm_def.category, 'value', perm_def.category)
            Permission.objects.update_or_create(
                code=perm_def.code,
                defaults={
                    'name': perm_def.name,
                    'description': perm_def.description,
                    'category': category_value,
                    'sort_order': perm_def.sort_order,
                    'is_system': True,
                },
            )

    permissions = list(Permission.objects.filter(code__in=ksef_codes))
    for role in OrganizationRole.objects.filter(system_role_type__in=[SystemRoleType.OWNER, SystemRoleType.ADMIN]):
        for permission in permissions:
            OrganizationRolePermission.objects.get_or_create(role=role, permission=permission)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('multitenancy', '0027_delete_unused_dashboard_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KsefCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('encrypted_token', models.BinaryField(help_text='AES-256-GCM payload, see apps.ksef.crypto')),
                ('token_hint', models.CharField(help_text='Last characters of the token, for display', max_length=16)),
                (
                    'status',
                    models.CharField(
                        choices=[('VALID', 'Valid'), ('UNVERIFIED', 'Not verified'), ('INVALID', 'Invalid')],
                        max_length=16,
                    ),
                ),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='multitenancy.tenant',
                        verbose_name='Tenant',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='ksef_one_credential_per_tenant')],
            },
        ),
        migrations.RunPython(add_ksef_permissions, migrations.RunPython.noop),
    ]
