# Generated by Django 5.2.11 on 2026-10-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ksef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksefcredential',
            name='token_name',
            field=models.CharField(
                blank=True, default='', help_text='Name of the token in KSeF (not secret)', max_length=255
            ),
        ),
    ]
