# Generated by Django 5.2.11 on 2026-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0005_alter_ssoauditlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssosession',
            name='refresh_token_jti',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
