# Generated by Django 5.2.11 on 2026-10-04 21:55

import apps.sso.models
import django.db.models.deletion
import hashid_field.field
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0030_remove_passkeys_manage_permission'),
        ('sso', '0007_ksef_audit_event_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoauditlog',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('idp_config_created', 'IdP Configuration Created'),
                    ('idp_config_updated', 'IdP Configuration Updated'),
                    ('idp_config_deleted', 'IdP Configuration Deleted'),
                    ('idp_config_activated', 'IdP Configuration Activated'),
                    ('idp_config_deactivated', 'IdP Configuration Deactivated'),
                    ('sso_login_initiated', 'SSO Login Initiated'),
                    ('sso_login_success', 'SSO Login Success'),
                    ('sso_login_failed', 'SSO Login Failed'),
                    ('sso_logout', 'SSO Logout'),
                    ('user_provisioned', 'User Provisioned via JIT'),
                    ('user_updated', 'User Updated via SSO'),
                    ('group_mapping_applied', 'Group Mapping Applied'),
                    ('scim_user_created', 'SCIM User Created'),
                    ('scim_user_updated', 'SCIM User Updated'),
                    ('scim_user_deleted', 'SCIM User Deleted'),
                    ('scim_group_created', 'SCIM Group Created'),
                    ('scim_group_updated', 'SCIM Group Updated'),
                    ('scim_group_deleted', 'SCIM Group Deleted'),
                    ('sso_enforce_bypass', 'SSO Enforce Bypass Login'),
                    ('domain_added', 'SSO Domain Added'),
                    ('domain_verified', 'SSO Domain Verified'),
                    ('domain_removed', 'SSO Domain Removed'),
                    ('session_created', 'Session Created'),
                    ('session_revoked', 'Session Revoked'),
                    ('device_registered', 'Device Registered'),
                    ('device_removed', 'Device Removed'),
                    ('passkey_registered', 'Passkey Registered'),
                    ('passkey_removed', 'Passkey Removed'),
                    ('passkey_auth_success', 'Passkey Auth Success'),
                    ('passkey_auth_failed', 'Passkey Auth Failed'),
                    ('passkey_clone_detected', 'Passkey Clone Detected'),
                    ('security_anomaly', 'Security Anomaly Detected'),
                    ('ksef_token_saved', 'KSeF Token Saved'),
                    ('ksef_token_tested', 'KSeF Token Tested'),
                    ('ksef_token_deleted', 'KSeF Token Deleted'),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('domain', models.CharField(help_text='Lowercase email domain, e.g. example.com', max_length=253)),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Pending verification'), ('verified', 'Verified')],
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'verification_token',
                    models.CharField(
                        default=apps.sso.models._generate_domain_verification_token, editable=False, max_length=64
                    ),
                ),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sso_domains',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('tenant', 'domain'), name='sso_tenant_domain_unique'),
                    models.UniqueConstraint(
                        condition=models.Q(('status', 'verified')),
                        fields=('domain',),
                        name='sso_verified_domain_unique',
                    ),
                ],
            },
        ),
    ]
