# Generated by Django 5.2.11 on 2026-10-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0009_passkey_management_audit_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthnchallenge',
            name='browser_binding',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
