# Generated by Django 5.2.11 on 2026-10-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0010_connection_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdomain',
            name='first_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
