# Generated by Django 5.2.11 on 2026-10-08 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0011_webauthnchallenge_sso_challenge_expiry_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='passkeymanagementgrant',
            index=models.Index(fields=['expires_at'], name='sso_grant_expiry_idx'),
        ),
    ]
