# Generated by Django 5.2.11 on 2026-10-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0011_domain_record_grace_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantssoconnection',
            name='oidc_trust_unverified_email',
            field=models.BooleanField(
                default=False,
                help_text='Accept OIDC logins whose email_verified claim is missing or false',
            ),
        ),
    ]
