# Generated by Django 5.2.11 on 2026-10-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0012_oidc_trust_unverified_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantssoconnection',
            name='oidc_client_secret_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
