# Generated by Django 5.2.11 on 2026-10-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0012_passkeymanagementgrant_sso_grant_expiry_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoauditlog',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('idp_config_created', 'IdP Configuration Created'),
                    ('idp_config_updated', 'IdP Configuration Updated'),
                    ('idp_config_deleted', 'IdP Configuration Deleted'),
                    ('idp_config_activated', 'IdP Configuration Activated'),
                    ('idp_config_deactivated', 'IdP Configuration Deactivated'),
                    ('sso_login_initiated', 'SSO Login Initiated'),
                    ('sso_login_success', 'SSO Login Success'),
                    ('sso_login_failed', 'SSO Login Failed'),
                    ('sso_logout', 'SSO Logout'),
                    ('user_provisioned', 'User Provisioned via JIT'),
                    ('user_updated', 'User Updated via SSO'),
                    ('group_mapping_applied', 'Group Mapping Applied'),
                    ('scim_user_created', 'SCIM User Created'),
                    ('scim_user_updated', 'SCIM User Updated'),
                    ('scim_user_deleted', 'SCIM User Deleted'),
                    ('scim_group_created', 'SCIM Group Created'),
                    ('scim_group_updated', 'SCIM Group Updated'),
                    ('scim_group_deleted', 'SCIM Group Deleted'),
                    ('sso_enforce_bypass', 'SSO Enforce Bypass Login'),
                    ('session_created', 'Session Created'),
                    ('session_revoked', 'Session Revoked'),
                    ('device_registered', 'Device Registered'),
                    ('device_removed', 'Device Removed'),
                    ('passkey_registered', 'Passkey Registered'),
                    ('passkey_removed', 'Passkey Removed'),
                    ('passkey_auth_success', 'Passkey Auth Success'),
                    ('passkey_auth_failed', 'Passkey Auth Failed'),
                    ('passkey_reauth_success', 'Passkey Management Authentication Success'),
                    ('passkey_reauth_failed', 'Passkey Management Authentication Failed'),
                    ('passkey_clone_detected', 'Passkey Clone Detected'),
                    ('security_anomaly', 'Security Anomaly Detected'),
                    ('ksef_token_saved', 'KSeF Token Saved'),
                    ('ksef_token_tested', 'KSeF Token Tested'),
                    ('ksef_token_deleted', 'KSeF Token Deleted'),
                    ('account_reclaimed', 'Account Reclaimed by Support'),
                ],
                max_length=50,
            ),
        ),
    ]
