# Generated by Django 5.2.11 on 2026-10-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0015_alter_ssoauditlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passkeymanagementgrant',
            name='action',
            field=models.CharField(
                choices=[
                    ('register', 'Register'),
                    ('delete', 'Delete'),
                    ('otp_setup', 'OTP Setup'),
                    ('otp_disable', 'OTP Disable'),
                    ('password_set', 'Password Set'),
                ],
                max_length=20,
            ),
        ),
    ]
