# Generated by Django 5.2.11 on 2026-10-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0016_alter_passkeymanagementgrant_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='passkeymanagementgrant',
            name='credential_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='passkeymanagementgrant',
            name='action',
            field=models.CharField(
                choices=[
                    ('register', 'Register'),
                    ('delete', 'Delete'),
                    ('otp_setup', 'OTP Setup'),
                    ('otp_disable', 'OTP Disable'),
                    ('password_set', 'Password Set'),
                    ('account_delete', 'Delete Account'),
                ],
                max_length=20,
            ),
        ),
    ]
