# Generated by Django 5.2.11 on 2026-09-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0023_alter_permission_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='actor_type',
            field=models.CharField(
                choices=[
                    ('USER', 'User'),
                    ('AI_AGENT', 'AI Agent'),
                    ('SUPERUSER', 'Superuser'),
                    ('SYSTEM:sync', 'System (Sync)'),
                    ('SYSTEM:import', 'System (Import)'),
                    ('SYSTEM:scheduled_task', 'System (Scheduled Task)'),
                    ('SYSTEM:migration', 'System (Migration)'),
                ],
                default='USER',
                help_text='Type of actor that performed the action',
                max_length=30,
            ),
        ),
    ]
