# Generated by Django 5.2.11 on 2026-09-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0024_alter_actionlog_actor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='nip',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='NIP'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='regon',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='REGON'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vat_status',
            field=models.CharField(
                blank=True,
                choices=[('ACTIVE', 'Active'), ('EXEMPT', 'Exempt'), ('NOT_REGISTERED', 'Not registered')],
                default='',
                max_length=20,
            ),
        ),
    ]
