# Generated by Django 5.2.11 on 2026-09-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0025_tenant_company_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(choices=[('PL', 'Poland')], default='PL', max_length=2),
        ),
    ]
