# Generated by Django 5.2.11 on 2026-10-03 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0027_delete_unused_dashboard_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationOnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_data', models.JSONField(blank=True, default=dict)),
                ('respondent_role', models.CharField(blank=True, default='', max_length=40)),
                ('customer_type', models.CharField(blank=True, default='', max_length=40)),
                ('revenue_models', models.JSONField(blank=True, default=list)),
                ('cost_drivers', models.JSONField(blank=True, default=list)),
                ('pricing', models.CharField(blank=True, default='', max_length=80)),
                ('main_goal', models.CharField(blank=True, default='', max_length=120)),
                ('current_step', models.PositiveSmallIntegerField(default=2)),
                ('is_required', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'draft_owner',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='organization_onboarding_draft',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'tenant',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='onboarding_profile',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('draft_owner__isnull', True), ('tenant__isnull', False)),
                            models.Q(('draft_owner__isnull', False), ('tenant__isnull', True)),
                            _connector='OR',
                        ),
                        name='onboarding_tenant_or_draft_owner',
                    )
                ],
            },
        ),
    ]
