# Generated by Django 5.2.11 on 2026-10-03 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0029_onboarding_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationonboardingprofile',
            name='company_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organizationonboardingprofile',
            name='draft_owner',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='organization_onboarding_draft',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='organizationonboardingprofile',
            name='tenant',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='onboarding_profile',
                to='multitenancy.tenant',
            ),
        ),
        migrations.AddConstraint(
            model_name='organizationonboardingprofile',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('draft_owner__isnull', True), ('tenant__isnull', False)),
                    models.Q(('draft_owner__isnull', False), ('tenant__isnull', True)),
                    _connector='OR',
                ),
                name='onboarding_tenant_or_draft_owner',
            ),
        ),
    ]
