# Generated by Django 5.2.11 on 2026-10-09 19:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0030_remove_passkeys_manage_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCleanup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(blank=True, max_length=64)),
                (
                    'resource_type',
                    models.CharField(
                        choices=[
                            ('export_file', 'Backup or activity export file'),
                            ('document_file', 'Document file'),
                            ('backup_key', 'Backup encryption key'),
                        ],
                        max_length=20,
                    ),
                ),
                ('resource_path', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'indexes': [
                    models.Index(
                        condition=models.Q(('completed_at__isnull', True)),
                        fields=['next_attempt_at'],
                        name='resource_cleanup_due_idx',
                    )
                ],
            },
        ),
    ]
