# Generated by Django 5.2.11 on 2026-10-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0031_resource_cleanup_outbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecleanup',
            name='resource_type',
            field=models.CharField(
                choices=[
                    ('export_file', 'Backup or activity export file'),
                    ('document_file', 'Document file'),
                    ('backup_key', 'Backup encryption key'),
                    ('export_prefix', 'Organization backup or export directory'),
                    ('document_prefix', 'Organization document directory'),
                ],
                max_length=20,
            ),
        ),
    ]
