# Generated by Django 5.2.11 on 2026-10-03 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0027_delete_unused_dashboard_permissions'),
        ('multitenancy', '0031_remove_onboarding_ksef'),
    ]

    operations = []
