# Generated by Django 5.2.11 on 2026-10-09 20:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0032_organization_storage_prefix_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDeletionDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(max_length=64)),
                (
                    'channel',
                    models.CharField(choices=[('email', 'Email'), ('in_app', 'In-app notification')], max_length=16),
                ),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('language', models.CharField(default='en', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=120)),
                (
                    'issuer',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='organization_deletion_deliveries_issued',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'recipient',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='organization_deletion_deliveries',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        condition=models.Q(('completed_at__isnull', True)),
                        fields=['next_attempt_at'],
                        name='org_delivery_due_idx',
                    )
                ],
            },
        ),
    ]
