# Generated by Django 5.2.11 on 2026-10-10 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_actor_snapshots(apps, schema_editor):
    ActionLog = apps.get_model('multitenancy', 'ActionLog')
    UserProfile = apps.get_model('users', 'UserProfile')
    for profile in UserProfile.objects.using(schema_editor.connection.alias).all().iterator():
        ActionLog.objects.using(schema_editor.connection.alias).filter(actor_user_id=profile.user_id).update(
            actor_id_snapshot=str(profile.user_id),
            actor_name_snapshot=f'{profile.first_name} {profile.last_name}'.strip(),
        )


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0033_organization_deletion_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='actor_id_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='actor_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_actor_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='actionlogexport',
            name='requested_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='action_log_exports',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='resourcecleanup',
            name='resource_type',
            field=models.CharField(
                choices=[
                    ('export_file', 'Backup or activity export file'),
                    ('document_file', 'Document file'),
                    ('backup_key', 'Backup encryption key'),
                    ('export_prefix', 'Organization backup or export directory'),
                    ('document_prefix', 'Organization document directory'),
                    ('avatar_file', 'Personal avatar file'),
                    ('user_export_prefix', 'Personal export directory'),
                    ('legacy_user_export', 'Legacy personal exports'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='creator',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
