# Generated by Django 5.2.11 on 2026-10-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0035_alter_resourcecleanup_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecleanup',
            name='resource_type',
            field=models.CharField(
                choices=[
                    ('export_file', 'Backup or activity export file'),
                    ('document_file', 'Document file'),
                    ('backup_key', 'Backup encryption key'),
                    ('export_prefix', 'Organization backup or export directory'),
                    ('document_prefix', 'Organization document directory'),
                    ('avatar_file', 'Personal avatar file'),
                    ('user_avatar_prefix', 'Personal avatar directory'),
                    ('account_marker', 'External account deletion marker'),
                    ('user_export_prefix', 'Personal export directory'),
                    ('legacy_user_export', 'Legacy personal exports'),
                ],
                max_length=20,
            ),
        ),
    ]
