# Generated by Django 5.2.11 on 2026-10-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0036_alter_resourcecleanup_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecleanup',
            name='account_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
