# Generated by Django 5.2.11 on 2026-09-26 13:36

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import hashid_field.field
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('multitenancy', '0023_alter_permission_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                (
                    'kind',
                    models.CharField(
                        choices=[('REVENUE', 'Revenue'), ('COST', 'Cost'), ('BOTH', 'Revenue and cost')], max_length=16
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='children',
                        to='klarvido.category',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='klarvido_%(class)s_set',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('legal_name', models.CharField(max_length=255)),
                ('tax_identifier', models.CharField(blank=True, max_length=32)),
                ('regon', models.CharField(blank=True, max_length=20)),
                ('pkd_code', models.CharField(blank=True, max_length=16)),
                ('country_code', models.CharField(default='PL', max_length=2)),
                ('default_currency', models.CharField(default='PLN', max_length=3)),
                (
                    'tenant',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='klarvido_company_profile',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Klarvido company profile',
                'verbose_name_plural': 'Klarvido company profiles',
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('tax_identifier', models.CharField(blank=True, max_length=32)),
                ('country_code', models.CharField(default='PL', max_length=2)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='klarvido_%(class)s_set',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'source_system',
                    models.CharField(
                        choices=[
                            ('MOCK', 'Mock data'),
                            ('KSEF', 'KSeF'),
                            ('GUS', 'GUS'),
                            ('REGON', 'REGON'),
                            ('NBP', 'NBP'),
                            ('MANUAL', 'Manual'),
                        ],
                        max_length=16,
                    ),
                ),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('schema_version', models.CharField(max_length=32)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('PROCESSING', 'Processing'),
                            ('COMPLETED', 'Completed'),
                            ('PARTIAL', 'Partial'),
                            ('FAILED', 'Failed'),
                        ],
                        default='PENDING',
                        max_length=16,
                    ),
                ),
                ('data_as_of', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='klarvido_%(class)s_set',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'invoice_type',
                    models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase')], max_length=16),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('ISSUED', 'Issued'), ('CORRECTED', 'Corrected'), ('CANCELLED', 'Cancelled')],
                        default='ISSUED',
                        max_length=16,
                    ),
                ),
                ('document_number', models.CharField(max_length=128)),
                ('issue_date', models.DateField()),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    'correction_of',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='corrections',
                        to='klarvido.invoice',
                    ),
                ),
                (
                    'counterparty',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='klarvido.counterparty'
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='klarvido_%(class)s_set',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('position', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('unit_price_net', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    'tax_rate',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0')),
                            django.core.validators.MaxValueValidator(Decimal('100')),
                        ],
                    ),
                ),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    'category_assignment_source',
                    models.CharField(
                        choices=[
                            ('UNASSIGNED', 'Unassigned'),
                            ('SOURCE', 'Source system'),
                            ('RULE', 'Classification rule'),
                            ('USER', 'User'),
                        ],
                        default='UNASSIGNED',
                        max_length=16,
                    ),
                ),
                (
                    'category_confidence',
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0')),
                            django.core.validators.MaxValueValidator(Decimal('1')),
                        ],
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='invoice_lines',
                        to='klarvido.category',
                    ),
                ),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='klarvido.invoice'
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='klarvido_%(class)s_set',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'source_system',
                    models.CharField(
                        choices=[
                            ('MOCK', 'Mock data'),
                            ('KSEF', 'KSeF'),
                            ('GUS', 'GUS'),
                            ('REGON', 'REGON'),
                            ('NBP', 'NBP'),
                            ('MANUAL', 'Manual'),
                        ],
                        max_length=16,
                    ),
                ),
                ('record_type', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=255)),
                ('schema_version', models.CharField(max_length=32)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('payload_checksum', models.CharField(max_length=64)),
                ('raw_payload', models.JSONField(default=dict)),
                (
                    'validation_status',
                    models.CharField(
                        choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('WARNING', 'Warning')],
                        default='VALID',
                        max_length=16,
                    ),
                ),
                ('validation_messages', models.JSONField(blank=True, default=list)),
                (
                    'data_import',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='records', to='klarvido.dataimport'
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='klarvido_%(class)s_set',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_record',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='invoice',
                to='klarvido.sourcerecord',
            ),
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('MONTH', 'Month'),
                            ('QUARTER', 'Quarter'),
                            ('HALF_YEAR', 'Half year'),
                            ('YEAR', 'Year'),
                            ('CUSTOM', 'Custom'),
                        ],
                        max_length=16,
                    ),
                ),
                ('label', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='klarvido_%(class)s_set',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'ordering': ['start_date', 'end_date'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('tenant', 'start_date', 'end_date'), name='klarvido_unique_accounting_period'
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('end_date__gte', models.F('start_date'))),
                        name='klarvido_period_dates_ordered',
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='klarvido_unique_category_code'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['tenant', 'name'], name='klarvido_co_tenant__e19120_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['tenant', 'is_customer'], name='klarvido_co_tenant__d9ae28_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['tenant', 'is_supplier'], name='klarvido_co_tenant__a92743_idx'),
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.CheckConstraint(
                condition=models.Q(('is_customer', True), ('is_supplier', True), _connector='OR'),
                name='klarvido_counterparty_has_role',
            ),
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(
                condition=models.Q(('tax_identifier', ''), _negated=True),
                fields=('tenant', 'tax_identifier'),
                name='klarvido_unique_counterparty_tax_id',
            ),
        ),
        migrations.AddIndex(
            model_name='dataimport',
            index=models.Index(
                fields=['tenant', 'source_system', '-created_at'], name='klarvido_da_tenant__6417f7_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='dataimport',
            index=models.Index(fields=['tenant', 'status'], name='klarvido_da_tenant__43ffc7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['tenant', 'category'], name='klarvido_in_tenant__5180f4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['tenant', 'invoice'], name='klarvido_in_tenant__b8a326_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(
                fields=('invoice', 'position'), name='klarvido_unique_invoice_line_position'
            ),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        'gross_amount',
                        django.db.models.expressions.CombinedExpression(
                            models.F('net_amount'), '+', models.F('tax_amount')
                        ),
                    )
                ),
                name='klarvido_invoice_line_totals_match',
            ),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(
                fields=['tenant', 'source_system', 'record_type'], name='klarvido_so_tenant__4960a6_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['tenant', 'validation_status'], name='klarvido_so_tenant__180c5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'source_system', 'record_type', 'external_id'), name='klarvido_unique_source_record'
            ),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'invoice_type', 'issue_date'], name='klarvido_in_tenant__ae8a44_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'counterparty', 'issue_date'], name='klarvido_in_tenant__385430_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status'], name='klarvido_in_tenant__83c5ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'invoice_type', 'counterparty', 'document_number'),
                name='klarvido_unique_invoice_number',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        'gross_amount',
                        django.db.models.expressions.CombinedExpression(
                            models.F('net_amount'), '+', models.F('tax_amount')
                        ),
                    )
                ),
                name='klarvido_invoice_totals_match',
            ),
        ),
    ]
