# Generated by Django 5.2.11 on 2026-09-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_useravatar_original_alter_useravatar_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_welcome_modal',
            field=models.BooleanField(default=False),
        ),
    ]
