# Generated by Django 5.2.11 on 2026-09-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_userprofile_has_seen_welcome_modal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(
                choices=[
                    ('en', 'English'),
                    ('pl', 'Polish'),
                    ('de', 'German'),
                    ('fr', 'French'),
                    ('es', 'Spanish'),
                    ('zh', 'Chinese'),
                    ('hi', 'Hindi'),
                    ('ar', 'Arabic'),
                ],
                default='en',
                help_text="User's preferred language for emails and notifications",
                max_length=5,
            ),
        ),
    ]
