# Generated by Django 5.2.11 on 2026-10-05 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0028_organization_onboarding_profile'),
        ('users', '0005_alter_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='default_for_profiles',
                to='multitenancy.tenant',
            ),
        ),
    ]
