# Generated by Django 5.2.11 on 2026-10-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_locked_until',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
