# Generated by Django 5.2.11 on 2026-10-06 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_otp_attempt_limits'),
        ('users', '0006_userprofile_default_organization'),
    ]

    operations = []
