# Generated by Django 5.2.11 on 2026-10-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_django', '0010_uid_db_index'),
        ('sso', '0013_alter_ssoauditlog_event_type'),
        ('users', '0008_pending_social_account_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccountUnlinkChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_version', models.CharField(max_length=64)),
                (
                    'association',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth'),
                ),
                (
                    'challenge',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sso.webauthnchallenge'),
                ),
            ],
        ),
    ]
