# Generated by Django 5.2.11 on 2026-10-08 20:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_otp_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupEmailCooldown',
            fields=[
                ('recipient_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_sent_at', models.DateTimeField(null=True)),
                ('day_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('daily_count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEmailOutbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('kind', models.CharField(max_length=40)),
                ('language', models.CharField(default='en', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=40)),
                (
                    'user',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
