# Generated by Django 5.2.11 on 2026-10-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_signupemailcooldown_securityemailoutbox'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='securityemailoutbox',
            index=models.Index(
                condition=models.Q(
                    ('cancelled_at__isnull', True), ('failed_at__isnull', True), ('sent_at__isnull', True)
                ),
                fields=['next_attempt_at'],
                name='users_security_email_due_idx',
            ),
        ),
    ]
