# Generated by Django 5.2.11 on 2026-10-08 21:26

import django.utils.timezone
from django.db import migrations, models


def encrypt_existing_seeds(apps, schema_editor):
    from apps.users.services.otp_crypto import encrypt_seed, load_keys
    load_keys()  # Configuration is required even on an empty database.
    User = apps.get_model('users', 'User')
    alias = schema_editor.connection.alias
    for account in User.objects.using(alias).all().iterator(chunk_size=500):
        User.objects.using(alias).filter(pk=account.pk).update(
            otp_seed_encrypted=encrypt_seed(account.pk, 'active', account.otp_base32),
            otp_pending_seed_encrypted=encrypt_seed(account.pk, 'pending', account.otp_pending_base32),
        )


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0012_securityemailoutbox_users_security_email_due_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetEmailLimit',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_queued_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='otp_pending_seed_encrypted',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_seed_encrypted',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.RunPython(encrypt_existing_seeds),
        migrations.RemoveField(
            model_name='user',
            name='otp_auth_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_base32',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_pending_auth_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_pending_base32',
        ),
    ]
