# Generated by Django 5.2.11 on 2026-10-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0013_resetemaillimit_remove_user_otp_auth_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordFailureBudget',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
