# Generated by Django 5.2.11 on 2026-10-10 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0014_passwordfailurebudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=64, unique=True)),
                ('actor_id', models.CharField(max_length=64)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
