# Generated by Django 5.2.11 on 2026-10-10 07:00

import common.storages
from django.db import migrations, models


def backfill_avatar_accounts(apps, schema_editor):
    Profile = apps.get_model('users', 'UserProfile')
    Avatar = apps.get_model('users', 'UserAvatar')
    for profile in Profile.objects.using(schema_editor.connection.alias).exclude(avatar_id=None).iterator():
        Avatar.objects.using(schema_editor.connection.alias).filter(pk=profile.avatar_id).update(account_id=str(profile.user_id))


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0015_accountdeletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='account_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.RunPython(backfill_avatar_accounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='useravatar',
            name='original',
            field=models.ImageField(
                null=True,
                storage=common.storages.PublicS3Boto3StorageWithCDN(),
                upload_to=common.storages.UserAvatarPathGenerator('original'),
            ),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='thumbnail',
            field=models.ImageField(
                null=True,
                storage=common.storages.PublicS3Boto3StorageWithCDN(),
                upload_to=common.storages.UserAvatarPathGenerator('thumbnails'),
            ),
        ),
    ]
