name: 'Backend'

on:
  push:
    branches: ['**']
    paths:
      - 'packages/backend/**'
      - 'docker-compose.yml'
      - 'docker-compose.ci.yml'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/backend.yml'
      - '.github/docker/**'
      - '.github/workflows/actions/setup/**'

env:
  SB_BACKEND_BASE_IMAGE: python:3.11-slim-bullseye
  SB_MIRROR_REPOSITORY: mirror.gcr.io/
  SB_PULL_THROUGH_CACHE_REPOSITORY: mirror.gcr.io/library/

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup
        with:
          node-version: 22

      - shell: bash
        run: pnpm install
          --include-workspace-root
          --frozen-lockfile
          --filter=backend...

      - name: Lint infra
        shell: bash
        run: pnpm nx run backend:lint:js

      - name: Lint & test backend
        shell: bash
        run: pnpm nx run backend:test

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        if: env.SONAR_ORGANIZATION != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
          SONAR_BACKEND_PROJECT_KEY: ${{ vars.SONAR_BACKEND_PROJECT_KEY }}
        with:
          projectBaseDir: packages/backend
