name: 'Docs'

on:
  push:
    branches: ['**']
    paths:
      - 'packages/internal/docs/**'
      - 'packages/backend/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/docs.yml'
      - 'docker-compose.ci.yml'
      - '.github/docker/**'
      - '.github/workflows/actions/setup/**'

env:
  SB_BACKEND_BASE_IMAGE: python:3.11-slim-bullseye
  SB_MIRROR_REPOSITORY: mirror.gcr.io/
  SB_PULL_THROUGH_CACHE_REPOSITORY: mirror.gcr.io/library/

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup
        with:
          node-version: 22

      - shell: bash
        run: pnpm install
          --include-workspace-root
          --frozen-lockfile
          --filter=docs...
          --filter=backend...

      - name: Lint
        shell: bash
        run: pnpm nx run docs:lint

      - name: Build
        shell: bash
        run: pnpm nx run docs:build
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
